### ISSUE TITLE
New feature: Present xfailed and xpassed in report-portal plugin

### ISSUE THREAD

**Issue by claes-arvidson** [reportportal/reportportal#1166]
Hi,
We are around 200 software developers at our company that will start using the report-portal plugin. However, in order for us to be satisfied with this plugin we would like to be able to present two columns: "xfailed" and "xpassed" so that they are not included in the "Passed and "Skipped" column. This would make us lose a lot of debug/evaluation time when running nightly runs on Jenkins for around 20 repositories with autotests. 

To reproduce one could write a small simple pytest test case:
test_xfail.py
```
@pytest.mark.xfail(reason='This one will fail and print as xfailed in stdout but as skipped column in report-portal.')
def test_failure():
    assert 0

@pytest.mark.xfail(reason='This one will pass and print as xpassed in stdout but as passed column in report-portal.')
def test_passed():
    assert 1
```

**Comment by claes-arvidson** [comment]
> @claes-arvidson What is the difference between your "xpassed" result and regular "passed" result? When you mark your test with the "xfail" marker, it means the results of that test will not impact the whole execution results and the test itself will be reported as "skipped" one. This situation is [already supported](https://github.com/reportportal/agent-python-pytest/blob/8a6c2fdac4292762baa12cd42ebe65c990de1089/pytest_reportportal/listener.py#L69) in the plugin.
> 
> Anyways, new columns for the UI should be requested at [reportportal](https://github.com/reportportal/reportportal) project, not here. This agent is about reporting of Pytest results to the API provided by the RP.

Thank you, I should rather create my issue there. This is not regarding the API, rather getting new UI columns.

**Comment by evjlobanova** [comment]
@claes-arvidson Actually we do not have plans to add new columns to the main page, and also to add new custom statuses. 
Because it can influence on our existing UI and Back-end logic.

Could you please explain what business logic have xfailed and xpassed?  How do you plan to use it in the analysis?


For now, you can handle this situation with existing tools:

- attributes: add to executions needed attributes - f.i. "status: xpassed"
- description: add this info to description
- defect types

**Comment by claes-arvidson** [comment]
@evjlobanova We have test cases that intermittently fails due to some timeouts trigger when communicating via http-requests where timing can differ from one run to another. In these cases we want to mark them as xfailed, write an issue and then remove the xfailed pytest-marker as soon as we have fixed the test case.

It is a huge issue currently to mark a test case as xfail via "@pytest.mark.xfail" as the testcase either is considered to be of type "Passed" if it indeed passes and of type "Skipped" if it fails. This results in the total amount of run tests seen in report-portal differs from one run to another making it very confusing why the total number differs. The reason why this is a problem is because we run nightly CI jobs on jenkins where new commits of our test framework can be updated and we want to always have control on the total amount of tests running and be aware when it changes. A simple solution would just be to create columns with "Xfailed" and "Xpassed" where these are not included in the total amount of test cases run in a sequence. That way the total amount will remain unaffected.

**Comment by evjlobanova** [comment]
@claes-arvidson definitely it is not a simple solution) these changes will affect the current logic of ReportPortal. Our application supports different test frameworks, so that we need to have a universal solution for different tests.

I will discuss it with a team internally, but anyway you for now the best option is to find a way how to use exsisting tools in ReportPortal.

For instance, you can report xfailed test as skipped with Defect type "Xfailed due to timeout"
So that you will see the number of xfailed test cases on All launches page.

**Comment by MaryiaRymarchyk** [comment]
Hi @claes-arvidson, did you find working solution for your project? 
Ticket is quite old  however we still don't plan to change current behavior for statuses and additional columns on the main page.

**Comment by MaryiaRymarchyk** [comment]
Seems that there are no remain actions from ReportPortal side.
Therefore, ticket will be closed.
