### ISSUE TITLE
[v5] 504 Gateway Time-out while importing launch with a lot of tests in the junit xml

### ISSUE THREAD

**Issue by obaranov** [reportportal/reportportal#1515]
**Describe the bug**
I'm trying to import junit XML with a large number of tests (around 3500) to the project. I use the Import button from UI or this API call: 

```
curl -X POST "https://reportportal-xyz.com/api/v1/myproject/launch/import" \
    -H  "accept: */*" \
    -H  "Content-Type: multipart/form-data" \
    -H  "Authorization: bearer *********" \
    -F "file=@/tmp/results.zip"
```

And after 30 seconds I'm getting the response: 

```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 58313    0     0  100 58313      0  48826  0:00:01  0:00:01 --:--:-- 48797
100 58313    0     0  100 58313      0  26550  0:00:02  0:00:02 --:--:-- 26542
100 58313    0     0  100 58313      0  18237  0:00:03  0:00:03 --:--:-- 18234
100 58313    0     0  100 58313      0  13888  0:00:04  0:00:04 --:--:-- 13887
100 58313    0     0  100 58313      0  11210  0:00:05  0:00:05 --:--:-- 11611
100 58313    0     0  100 58313      0   9401  0:00:06  0:00:06 --:--:--     0
100 58313    0     0  100 58313      0   8094  0:00:07  0:00:07 --:--:--     0
100 58313    0     0  100 58313      0   7106  0:00:08  0:00:08 --:--:--     0
100 58313    0     0  100 58313      0   6333  0:00:09  0:00:09 --:--:--     0
100 58313    0     0  100 58313      0   5712  0:00:10  0:00:10 --:--:--     0
100 58313    0     0  100 58313      0   5202  0:00:11  0:00:11 --:--:--     0
100 58313    0     0  100 58313      0   4775  0:00:12  0:00:12 --:--:--     0
100 58313    0     0  100 58313      0   4413  0:00:13  0:00:13 --:--:--     0
100 58313    0     0  100 58313      0   4103  0:00:14  0:00:14 --:--:--     0
100 58313    0     0  100 58313      0   3832  0:00:15  0:00:15 --:--:--     0
100 58313    0     0  100 58313      0   3596  0:00:16  0:00:16 --:--:--     0
100 58313    0     0  100 58313      0   3386  0:00:17  0:00:17 --:--:--     0
100 58313    0     0  100 58313      0   3200  0:00:18  0:00:18 --:--:--     0
100 58313    0     0  100 58313      0   3033  0:00:19  0:00:19 --:--:--     0
100 58313    0     0  100 58313      0   2883  0:00:20  0:00:20 --:--:--     0
100 58313    0     0  100 58313      0   2747  0:00:21  0:00:21 --:--:--     0
100 58313    0     0  100 58313      0   2623  0:00:22  0:00:22 --:--:--     0
100 58313    0     0  100 58313      0   2510  0:00:23  0:00:23 --:--:--     0
100 58313    0     0  100 58313      0   2406  0:00:24  0:00:24 --:--:--     0
100 58313    0     0  100 58313      0   2311  0:00:25  0:00:25 --:--:--     0
100 58313    0     0  100 58313      0   2222  0:00:26  0:00:26 --:--:--     0
100 58313    0     0  100 58313      0   2141  0:00:27  0:00:27 --:--:--     0
100 58313    0     0  100 58313      0   2064  0:00:28  0:00:28 --:--:--     0
100 58313    0     0  100 58313      0   1994  0:00:29  0:00:29 --:--:--     0
100 58313    0     0  100 58313      0   1928  0:00:30  0:00:30 --:--:--     0
100 58313    0     0  100 58313      0   1925  0:00:30  0:00:30 --:--:--     0
07:19:06  curl: (22) The requested URL returned error: 504 Gateway Time-out
```

When I go to the UI after that, I can see a new launch, but It looks like it is under processing by some backend workers. And after some time I can see a valid launch with all the tests. 

But anyways the 504 status code breaks our automation around importing results and we cannot get the launch UUID because of that. 

**Expected behavior**
We should be able to import large test suites to the report portal. I think there could be few options: 
1) Increase somehow the import timeout (eg by setting some special request headers) 
2) Refactor the import API behavior so it does not wait for the completion of all tests to be imported. Just create a new launch and return UUID back to the user in the response message. And then the backend will complete adding all the tests into the launch. 

Any workarounds are very welcome :) 

ReportPortal Version: 
Build: 5.3.5

**Comment by hadizia** [comment]
Hey I was wondering if you were able to solve this issue? Im facing a similar problem, not a gatweay time out but just a regular timeout (Connection timed out) when im sending multiple curl requests to post data. The connection is pretty flaky and sometimes it doesnt timeout at all whereas in some cases several testsuite uploads get timed out. I couldn't find a work around and was wondering if you had anythin?

**Comment by obaranov** [comment]
Yeah, we did a custom solution to workaround that issue. We parse an XML file with the test results and create all the testcases in the Report Portal one by one using rest API. Pretty ugly and complicated... but I can't imagine how we can workaround that import issue in a better way.

**Comment by irynakozak2** [comment]
Hi @obaranov! Please update RP to the latest released version and check if the issue still occurs. Thank you!

**Comment by obaranov** [comment]
@irynakozak2, the same problem is happening for the Build: 5.7.2.

**Comment by irynakozak2** [comment]
@obaranov thank you for the response. We put a spike into our backlog and plan to fix that in the upcoming 5.7.5 version.

**Comment by rujutashinde** [comment]
Hi @irynakozak2 , do you have an update if this issue is going to be fixed , and in what release?
We use the launch/import api and due to this 504 response on an actual successful launch, it is breaking our tool.

Thanks!!

**Comment by rujutashinde** [comment]
Thanks @Oleksii-kh89 for the update. If you have a link to docs that we can monitor for the upcoming changes it would be helpful.

**Comment by Oleksii-kh89** [comment]
@rujutashinde 

Thank you for your response. We write about all important updates on our  [Slack] channel (https://slack.epmrpp.reportportal.io/) and [Twitter](https://twitter.com/ReportPortal_io). About new version naming you can read [here](https://reportportal.io/blog/new-approach-to-versions-naming)

**Comment by irynakozak2** [comment]
@rujutashinde @obaranov @hadizia 
Hi everyone! We have released the 5.8([23.1](https://github.com/reportportal/reportportal/releases/tag/v23.1)) version with the fix. Please consider updating your ReportPortal and provide us feedback.

Thank you. Waiting for your reply.

**Comment by irynakozak2** [comment]
@rujutashinde @obaranov @hadizia 
Hello everyone! Long time no hear from you, so I close that issue for now. If that issue is still relevant for you after the upgrade - please reply to this ticket or consider creating a new one.
Thank you!

**Comment by irynakozak2** [comment]
@rujutashinde @obaranov @hadizia
Hello everyone! Long time no hear from you, so I close that issue for now. If that issue is still relevant for you after the upgrade - please reply to this ticket or consider creating a new one.
Thank you!

**Comment by nishant-shah-social** [comment]
@irynakozak2 unfortunately I am still facing this issue on reportportal.io. :(
