### ISSUE TITLE
[v5] SAML login redirects to http:// instead of https:// after successful OKTA authentication

### ISSUE THREAD

**Issue by sandeep-mm** [reportportal/reportportal#1660]
**Describe the bug**
SAML login redirects to http:// instead of https:// after successful OKTA authentication. Changing http:// -> https:// in the url works and completes the login.

**To Reproduce**
I start with https://<host> and use SAML login button to proceed with login but upon successful authentication, I get redirected to following: http://<host>/ui/#authSuccess?token=eyJhbGciOiJIUzI1NiIsInR5cCI6I[…]sP7kvJlIwWgh1Pmydqyox2iZ-Be8Dk&token_type=bearer

**Expected behavior**
If host has https:// enabled and the start point is https:// then upon successful authentication from OKTA, user should be redirected to https:// url and not http://. The url used in OKTA integration in both RP and OKTA side is https:// only.

**Screenshots**
OKTA integration in RP:
<img width="927" alt="Screen Shot 2022-02-02 at 4 39 13 PM" src="https://user-images.githubusercontent.com/51965904/152241952-02775b2e-dbc7-40ad-8c5a-cc64e4e37057.png">

RP app configuration in OKTA:
![image](https://user-images.githubusercontent.com/51965904/152243120-3824e31b-1939-4d22-b217-79b6f3ba7c17.png)

RP SAML login redirected to http after successful OKTA authentication:
![Screen Shot 2022-02-02 at 4 50 27 PM](https://user-images.githubusercontent.com/51965904/152243656-7d2f87c9-83ac-403f-b7c9-aa4d9d7153f2.png)

Simply modifying the url with auth token from http -> https works and user gets logged in.

**Desktop (please complete the following information):**
 - OS: OSX Monterey 12.2
 - Browser Chrome
 - Version 97
 - RP Version: 5.6.3

**Additional context**
I tried the solution mentioned in one of the other bugs that was fixed in RP version 5.6+ here - https://github.com/reportportal/reportportal/issues/1019#issuecomment-741642559

Adding "rpHost" via PUT call for plugin API works for notification plugin and password reset links in email become https instead of http BUT the same solution didn't work for saml plugin.

**Comment by sandeepnagra** [comment]
For now, I've just added a listener to port 80 with a redirect action to port 443 to avoid the issue I am getting but I guess this should be resolved at the application level as well so will keep the bug open

**Comment by vitalii-valkov-celsius** [comment]
I had similar issue and after debugging I found there is not problem in the app. The App just builds absolute redirect url based on incoming request. In this case the issue was caused by wrong X-Forwarded-* headers. My configuration is ALB->NGINX->APP. So, the container received wrong X-Forwarded-Proto, X-Forwarded-Schema, etc. I fixed it by using [use-forwarded-headers](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#use-forwarded-headers) config for NGINX.

**Comment by arnabnandy1706** [comment]
I am facing the same issue. And I cannot create redirect rule as I am using Classic AWS Load Balancer and it does not allow to create redirect rules.
How can this be resolved ?

**Comment by vitramir** [comment]
@arnabnandy1706 can you provide more information about your infrastructure? 

Classic LB -> ?

**Comment by MaryiaRymarchyk** [comment]
@arnabnandy1706  any updates from your side? is the issue still relevant ?
