### ISSUE TITLE
SAML Azure AD loging 403 with  Invalid characters (CR/LF) in header Location

### ISSUE THREAD

**Issue by fjogstad** [reportportal/reportportal#1989]
Issue: We get a 403 during SAML azure ad login where the uat service throws and  Invalid characters (CR/LF) in header Location exception. We have followed the SAML configuration on the documentation and both Azure and Reportportal looks ok.

Our setup: We run reportportal on with docker-compose on a linux VM in azure behind an Azure Web Application Firewall. Our WAF is the on who do the SSL termination and such the traffic is HTTP from the WAF to the traefic gateway.

Version:API Service: 5.7.4;Index Service: 5.7.3;Jobs Service: 5.7.4;Authorization Service: 5.7.4;Service UI: 5.7.4; 

```
 reportportal-uat-1               | 2023-04-26 03:46:55.666 DEBUG 1 --- [nio-9999-exec-9] o.s.security.web.FilterChainProxy        : Securing POST /saml/sp/SSO/alias/report-portal-sp
reportportal-uat-1               | 2023-04-26 03:46:55.666 DEBUG 1 --- [nio-9999-exec-9] s.s.w.c.SecurityContextPersistenceFilter : Set SecurityContextHolder to empty SecurityContext
reportportal-uat-1               | 2023-04-26 03:46:55.701 DEBUG 1 --- [nio-9999-exec-9] w.c.HttpSessionSecurityContextRepository : Did not store empty SecurityContext
reportportal-uat-1               | 2023-04-26 03:46:55.701 DEBUG 1 --- [nio-9999-exec-9] w.c.HttpSessionSecurityContextRepository : Did not store empty SecurityContext
reportportal-uat-1               | 2023-04-26 03:46:55.702 DEBUG 1 --- [nio-9999-exec-9] s.s.w.c.SecurityContextPersistenceFilter : Cleared SecurityContextHolder to complete request
reportportal-uat-1               | 2023-04-26 03:46:55.703 ERROR 1 --- [nio-9999-exec-9] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
reportportal-uat-1               | 
reportportal-uat-1               | java.lang.IllegalArgumentException: Invalid characters (CR/LF) in header Location
reportportal-uat-1               |      at org.springframework.util.Assert.isTrue(Assert.java:139) ~[spring-core-5.3.20.jar!/:5.3.20]
reportportal-uat-1               |      at org.springframework.security.web.firewall.FirewalledResponse.validateCrlf(FirewalledResponse.java:76) ~[spring-security-web-5.5.8.jar!/:5.5.8]
reportportal-uat-1               |      at org.springframework.security.web.firewall.FirewalledResponse.sendRedirect(FirewalledResponse.java:47) ~[spring-security-web-5.5.8.jar!/:5.5.8]
reportportal-uat-1               |      at javax.servlet.http.HttpServletResponseWrapper.sendRedirect(HttpServletResponseWrapper.java:138) ~[tomcat-embed-core-9.0.43.jar!/:4.0.FR]
reportportal-uat-1               |      at org.springframework.security.web.util.OnCommittedResponseWrapper.sendRedirect(OnCommittedResponseWrapper.java:136) ~[spring-security-web-5.5.8.jar!/:5.5.8]
reportportal-uat-1               |      at javax.servlet.http.HttpServletResponseWrapper.sendRedirect(HttpServletResponseWrapper.java:138) ~[tomcat-embed-core-9.0.43.jar!/:4.0.FR]
reportportal-uat-1               |      at org.springframework.security.web.util.OnCommittedResponseWrapper.sendRedirect(OnCommittedResponseWrapper.java:136) ~[spring-security-web-5.5.8.jar!/:5.5.8]
reportportal-uat-1               |      at com.epam.reportportal.auth.AuthFailureHandler.onAuthenticationFailure(AuthFailureHandler.java:36) ~[classes!/:na]
reportportal-uat-1               |      at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.unsuccessfulAuthentication(AbstractAuthenticationProcessingFilter.java:342) ~[spring-security-web-5.5.8.jar!/:5.5.8]
reportportal-uat-1               |      at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:240) ~[spring-security-web-5.5.8.jar!/:5.5.8]
reportportal-uat-1               |      at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212) ~[spring-security-web-5.5.8.jar!/:5.5.8]
reportportal-uat-1               |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.5.8.jar!/:5.5.8]
reportportal-uat-1               |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:111) ~[spring-web-5.3.20.jar!/:5.3.20]
reportportal-uat-1               |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.5.8.jar!/:5.5.8]
reportportal-uat-1               |      at org.springframework.security.saml.provider.service.SamlAuthenticationRequestFilter.doFilterInternal(SamlAuthenticationRequestFilter.java:89) ~[spring-security-saml2-core-2.0.0.M31.jar!/:2.0.0.M31]
reportportal-uat-1               |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.20.jar!/:5.3.20]
reportportal-uat-1               |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.5.8.jar!/:5.5.8]
reportportal-uat-1               |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:111) ~[spring-web-5.3.20.jar!/:5.3.20]
reportportal-uat-1               |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.5.8.jar!/:5.5.8]
reportportal-uat-1               |      at org.springframework.security.saml.provider.SamlMetadataFilter.doFilterInternal(SamlMetadataFilter.java:75) ~[spring-security-saml2-core-2.0.0.M31.jar!/:2.0.0.M31]
reportportal-uat-1               |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.20.jar!/:5.3.20]
reportportal-uat-1               |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.5.8.jar!/:5.5.8]
reportportal-uat-1               |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:111) ~[spring-web-5.3.20.jar!/:5.3.20]
reportportal-uat-1               |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.5.8.jar!/:5.5.8]
reportportal-uat-1               |      at org.springframework.security.saml.provider.config.ThreadLocalSamlConfigurationFilter.doFilterInternal(ThreadLocalSamlConfigurationFilter.java:42) ~[spring-security-saml2-core-2.0.0.M31.jar!/:2.0.0.M31]
reportportal-uat-1               |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.20.jar!/:5.3.20]
reportportal-uat-1               |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.5.8.jar!/:5.5.8]
reportportal-uat-1               |      at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103) ~[spring-security-web-5.5.8.jar!/:5.5.8]
reportportal-uat-1               |      at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89) ~[spring-security-web-5.5.8.jar!/:5.5.8]
reportportal-uat-1               |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.5.8.jar!/:5.5.8]
reportportal-uat-1               |      at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90) ~[spring-security-web-5.5.8.jar!/:5.5.8]
reportportal-uat-1               |      at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75) ~[spring-security-web-5.5.8.jar!/:5.5.8]
reportportal-uat-1               |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.20.jar!/:5.3.20]
reportportal-uat-1               |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.5.8.jar!/:5.5.8]
reportportal-uat-1               |      at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110) ~[spring-security-web-5.5.8.jar!/:5.5.8]
reportportal-uat-1               |      at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80) ~[spring-security-web-5.5.8.jar!/:5.5.8]
reportportal-uat-1               |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.5.8.jar!/:5.5.8]
reportportal-uat-1               |      at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55) ~[spring-security-web-5.5.8.jar!/:5.5.8]
reportportal-uat-1               |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.20.jar!/:5.3.20]
reportportal-uat-1               |      at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) ~[spring-security-web-5.5.8.jar!/:5.5.8]
reportportal-uat-1               |      at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211) ~[spring-security-web-5.5.8.jar!/:5.5.8]
reportportal-uat-1               |      at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183) ~[spring-security-web-5.5.8.jar!/:5.5.8]
reportportal-uat-1               |      at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354) ~[spring-web-5.3.20.jar!/:5.3.20]
reportportal-uat-1               |      at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267) ~[spring-web-5.3.20.jar!/:5.3.20]
reportportal-uat-1               |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.43.jar!/:9.0.43]
reportportal-uat-1               |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.43.jar!/:9.0.43]
reportportal-uat-1               |      at org.springframework.security.oauth2.client.filter.OAuth2ClientContextFilter.doFilter(OAuth2ClientContextFilter.java:64) ~[spring-security-oauth2-2.4.0.RELEASE.jar!/:na]
reportportal-uat-1               |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.43.jar!/:9.0.43]
reportportal-uat-1               |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.43.jar!/:9.0.43]
reportportal-uat-1               |      at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.20.jar!/:5.3.20]
reportportal-uat-1               |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.20.jar!/:5.3.20]
reportportal-uat-1               |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.43.jar!/:9.0.43]
reportportal-uat-1               |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.43.jar!/:9.0.43]
reportportal-uat-1               |      at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.20.jar!/:5.3.20]
reportportal-uat-1               |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.20.jar!/:5.3.20]
reportportal-uat-1               |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.43.jar!/:9.0.43]
reportportal-uat-1               |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.43.jar!/:9.0.43]
reportportal-uat-1               |      at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96) ~[spring-boot-actuator-2.5.14.jar!/:2.5.14]
reportportal-uat-1               |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.20.jar!/:5.3.20]
reportportal-uat-1               |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.43.jar!/:9.0.43]
reportportal-uat-1               |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.43.jar!/:9.0.43]
reportportal-uat-1               |      at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.20.jar!/:5.3.20]
reportportal-uat-1               |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.20.jar!/:5.3.20]
reportportal-uat-1               |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.43.jar!/:9.0.43]
reportportal-uat-1               |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.43.jar!/:9.0.43]
reportportal-uat-1               |      at org.springframework.web.filter.ForwardedHeaderFilter.doFilterInternal(ForwardedHeaderFilter.java:156) ~[spring-web-5.3.20.jar!/:5.3.20]
reportportal-uat-1               |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.20.jar!/:5.3.20]
reportportal-uat-1               |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.43.jar!/:9.0.43]
reportportal-uat-1               |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.43.jar!/:9.0.43]
reportportal-uat-1               |      at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.43.jar!/:9.0.43]
reportportal-uat-1               |      at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.43.jar!/:9.0.43]
reportportal-uat-1               |      at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) ~[tomcat-embed-core-9.0.43.jar!/:9.0.43]
reportportal-uat-1               |      at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) ~[tomcat-embed-core-9.0.43.jar!/:9.0.43]
reportportal-uat-1               |      at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.43.jar!/:9.0.43]
reportportal-uat-1               |      at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.43.jar!/:9.0.43]
reportportal-uat-1               |      at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346) ~[tomcat-embed-core-9.0.43.jar!/:9.0.43]
reportportal-uat-1               |      at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) ~[tomcat-embed-core-9.0.43.jar!/:9.0.43]
reportportal-uat-1               |      at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.43.jar!/:9.0.43]
reportportal-uat-1               |      at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:887) ~[tomcat-embed-core-9.0.43.jar!/:9.0.43]
reportportal-uat-1               |      at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1684) ~[tomcat-embed-core-9.0.43.jar!/:9.0.43]
reportportal-uat-1               |      at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.43.jar!/:9.0.43]
reportportal-uat-1               |      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
reportportal-uat-1               |      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
reportportal-uat-1               |      at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.43.jar!/:9.0.43]
reportportal-uat-1               |      at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
```

**Comment by drehelis** [comment]
@fjogstad Were you able to solve this?

**Comment by fjogstad** [comment]
Hi,
Github notifications went to my spam filter...

I have not been able to work around this, I have not had time to investigate further either so not sure if I still have this problem.

**Comment by MeirsPortal** [comment]
Hi,
We have upgraded to the latest RP version and still have this issue on Chrome browser, we tried changing the env value (RP_SAML_SESSION-LIVE) as recommended in issues ([#1876](https://github.com/reportportal/reportportal/issues/1876), [#259](https://github.com/reportportal/service-authorization/issues/259)), but it didn't help.
Currently using SAML in Edge browser - No '403' error there.

**Comment by abalasub-wm** [comment]
I had a similar issue with authorization. any updates on this ?


java.lang.IllegalArgumentException: Invalid characters (CR/LF) in header Location
        at org.springframework.util.Assert.isTrue(Assert.java:139) ~[spring-core-5.3.20.jar!/:5.3.20]

**Comment by raikbitters** [comment]
@fjogstad, there is a restriction for HTTP traffic. Could you switch from HTTP to HTTPS as a workaround?

**Comment by cailyoung** [comment]
We have the same issue.

**Comment by MeirsPortal** [comment]
I see that a lot of users are straggling with this issue.
Btw, it does not reproduce when using **Edge** browser - not sure why.
Is there a planed fix?

**Comment by alena-babrova** [comment]
Dear community,

Thank you for pointing out the issue and for your patience as well!
The issue is already fixed and will be available in **the next release (23.3)**.

Please, stay tuned.

**Comment by MeirsPortal** [comment]
Can't be more exited 🎉

**Comment by Kozovskaya** [comment]
Hello @fjogstad @drehelis @cobwebstech @abalasub-wm @cailyoung @MeirsPortal @dstewart25 
I'm pleased to let you know that the fix is already released!
https://github.com/reportportal/reportportal/releases/tag/v24.1

**Comment by MeirsPortal** [comment]
> Dear community,
> 
> Thank you for pointing out the issue and for your patience as well! The issue is already fixed and will be available in **the next release (24.1)**.
> 
> Please, stay tuned.

Still not working in v24.1 :(
![image](https://github.com/reportportal/reportportal/assets/115170014/0b764ae6-1c18-4abc-b6eb-0fd4ec224640)

**Comment by raikbitters** [comment]
@MeirsPortal I provide different Error messages. It doesn't look like a similar issue.
