### ISSUE TITLE
Missing RabbitMQ Queues

### ISSUE THREAD

**Issue by tomikonio** [reportportal/reportportal#2560]
**Describe the bug**
Looking into rabbitmq, we found that one of the API servers had some queues missing.  
In addition, the affected API server seemed to be unfunctional -> it did not produce nor consume to any of its queues.
This was fixed by restarting the specific API server.  

#### Problematic API server logs:
```
2025-06-03T08:25:37.996649107Z 2025-06-03 08:25:37.995 ERROR 1 --- [-8585-exec-2228] .r.r.c.e.r.ReportPortalExceptionResolver : ReportPortalExceptionResolver > Launch '0e60036b-d31f-4c22-94d8-4d4d1e96b883' not found. Did you use correct Launch ID?
2025-06-03T08:25:37.996651407Z
2025-06-03T08:25:37.996653952Z com.epam.reportportal.rules.exception.ReportPortalException: Launch '0e60036b-d31f-4c22-94d8-4d4d1e96b883' not found. Did you use correct Launch ID?
2025-06-03T08:25:37.996656337Z 	at com.epam.ta.reportportal.core.launch.impl.GetLaunchHandlerImpl.lambda$findLaunch$1(GetLaunchHandlerImpl.java:163)
2025-06-03T08:25:37.996658417Z 	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
2025-06-03T08:25:37.996660589Z 	at com.epam.ta.reportportal.core.launch.impl.GetLaunchHandlerImpl.findLaunch(GetLaunchHandlerImpl.java:163)
2025-06-03T08:25:37.996662533Z 	at com.epam.ta.reportportal.core.launch.impl.GetLaunchHandlerImpl.getLaunch(GetLaunchHandlerImpl.java:153)
2025-06-03T08:25:37.996664907Z 	at com.epam.ta.reportportal.core.launch.impl.GetLaunchHandlerImpl$$FastClassBySpringCGLIB$$21f6db8c.invoke(<generated>)
2025-06-03T08:25:37.996667238Z 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
2025-06-03T08:25:37.996669402Z 	at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
2025-06-03T08:25:37.996671664Z 	at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
2025-06-03T08:25:37.996673750Z 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
2025-06-03T08:25:37.996675930Z 	at com.epam.ta.reportportal.core.launch.impl.GetLaunchHandlerImpl$$EnhancerBySpringCGLIB$$ee058a71.getLaunch(<generated>)
2025-06-03T08:25:37.996678223Z 	at com.epam.ta.reportportal.ws.controller.LaunchController.getLaunchByUuidOldTimestamp(LaunchController.java:269)
2025-06-03T08:25:37.996680229Z 	at com.epam.ta.reportportal.ws.controller.LaunchController$$FastClassBySpringCGLIB$$702dfa6.invoke(<generated>)
2025-06-03T08:25:37.996682436Z 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
2025-06-03T08:25:37.996684486Z 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
2025-06-03T08:25:37.996686722Z 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
2025-06-03T08:25:37.996688764Z 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
2025-06-03T08:25:37.996691113Z 	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
2025-06-03T08:25:37.996693634Z 	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
2025-06-03T08:25:37.996695690Z 	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
2025-06-03T08:25:37.996698249Z 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
2025-06-03T08:25:37.996700566Z 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
2025-06-03T08:25:37.996702498Z 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
2025-06-03T08:25:37.996704667Z 	at com.epam.ta.reportportal.ws.controller.LaunchController$$EnhancerBySpringCGLIB$$c3b7fc91.getLaunchByUuidOldTimestamp(<generated>)
2025-06-03T08:25:37.996714631Z 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
2025-06-03T08:25:37.996716985Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
2025-06-03T08:25:37.996719160Z 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
2025-06-03T08:25:37.996724386Z 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
2025-06-03T08:25:37.996726833Z 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
2025-06-03T08:25:37.996729075Z 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:903)
2025-06-03T08:25:37.996731116Z 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:809)
2025-06-03T08:25:37.996761890Z 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
2025-06-03T08:25:37.996764248Z 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)
2025-06-03T08:25:37.996766442Z 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
2025-06-03T08:25:37.996768473Z 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
2025-06-03T08:25:37.996778994Z 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
2025-06-03T08:25:37.996781567Z 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:529)
2025-06-03T08:25:37.996783845Z 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
2025-06-03T08:25:37.996786003Z 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
2025-06-03T08:25:37.996788240Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
2025-06-03T08:25:37.996790608Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
2025-06-03T08:25:37.996793119Z 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
2025-06-03T08:25:37.996795377Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
2025-06-03T08:25:37.996797585Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
2025-06-03T08:25:37.996799681Z 	at org.springframework.web.multipart.support.MultipartFilter.doFilterInternal(MultipartFilter.java:125)
2025-06-03T08:25:37.996801824Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
2025-06-03T08:25:37.996803962Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
2025-06-03T08:25:37.996806166Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
2025-06-03T08:25:37.996808413Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:352)
2025-06-03T08:25:37.996810664Z 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:117)
2025-06-03T08:25:37.996812777Z 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83)
2025-06-03T08:25:37.996814865Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)
2025-06-03T08:25:37.996819587Z 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126)
2025-06-03T08:25:37.996821944Z 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120)
2025-06-03T08:25:37.996823950Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)
2025-06-03T08:25:37.996825927Z 	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:131)
2025-06-03T08:25:37.996828378Z 	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:85)
2025-06-03T08:25:37.996831078Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)
2025-06-03T08:25:37.996833354Z 	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100)
2025-06-03T08:25:37.996835730Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)
2025-06-03T08:25:37.996838130Z 	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:164)
2025-06-03T08:25:37.996840693Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)
2025-06-03T08:25:37.996842824Z 	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
2025-06-03T08:25:37.996845038Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)
2025-06-03T08:25:37.996847850Z 	at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter.doFilter(OAuth2AuthenticationProcessingFilter.java:182)
2025-06-03T08:25:37.996850082Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)
2025-06-03T08:25:37.996852311Z 	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107)
2025-06-03T08:25:37.996854650Z 	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93)
2025-06-03T08:25:37.996857126Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)
2025-06-03T08:25:37.996860168Z 	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
2025-06-03T08:25:37.996862901Z 	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
2025-06-03T08:25:37.996865473Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
2025-06-03T08:25:37.996868303Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)
2025-06-03T08:25:37.996878371Z 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:117)
2025-06-03T08:25:37.996881164Z 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
2025-06-03T08:25:37.996883642Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)
2025-06-03T08:25:37.996885795Z 	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62)
2025-06-03T08:25:37.996888054Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
2025-06-03T08:25:37.996890215Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)
2025-06-03T08:25:37.996894693Z 	at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)
2025-06-03T08:25:37.996896850Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
2025-06-03T08:25:37.996898970Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)
2025-06-03T08:25:37.996900971Z 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:225)
2025-06-03T08:25:37.996903168Z 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:190)
2025-06-03T08:25:37.996905235Z 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)
2025-06-03T08:25:37.996907823Z 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)
2025-06-03T08:25:37.996910100Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
2025-06-03T08:25:37.996912519Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
2025-06-03T08:25:37.996916982Z 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
2025-06-03T08:25:37.996919328Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
2025-06-03T08:25:37.996921364Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
2025-06-03T08:25:37.996923692Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
2025-06-03T08:25:37.996925960Z 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
2025-06-03T08:25:37.996928412Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
2025-06-03T08:25:37.996930717Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
2025-06-03T08:25:37.996933151Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
2025-06-03T08:25:37.996935556Z 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
2025-06-03T08:25:37.996937747Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
2025-06-03T08:25:37.996939870Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
2025-06-03T08:25:37.996942340Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
2025-06-03T08:25:37.996944530Z 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
2025-06-03T08:25:37.996946640Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
2025-06-03T08:25:37.996948686Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
2025-06-03T08:25:37.996950709Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
2025-06-03T08:25:37.996952844Z 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
2025-06-03T08:25:37.996955040Z 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
2025-06-03T08:25:37.996957220Z 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
2025-06-03T08:25:37.996959380Z 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
2025-06-03T08:25:37.996963803Z 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
2025-06-03T08:25:37.996966101Z 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
2025-06-03T08:25:37.996968224Z 	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:765)
2025-06-03T08:25:37.996970349Z 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
2025-06-03T08:25:37.996972650Z 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
2025-06-03T08:25:37.996974785Z 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
2025-06-03T08:25:37.996990773Z 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
2025-06-03T08:25:37.996993654Z 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794)
2025-06-03T08:25:37.996995961Z 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
2025-06-03T08:25:37.996998080Z 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
2025-06-03T08:25:37.997008949Z 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
2025-06-03T08:25:37.997010845Z 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
2025-06-03T08:25:37.997012673Z 	at java.base/java.lang.Thread.run(Thread.java:1583)
2025-06-03T08:25:37.997014208Z
2025-06-03T08:25:37.997017743Z 2025-06-03 08:25:37.996  WARN 1 --- [-8585-exec-2228] c.e.r.r.c.e.rest.RestExceptionHandler    : Resolved [com.epam.reportportal.rules.exception.ReportPortalException: Launch '0e60036b-d31f-4c22-94d8-4d4d1e96b883' not found. Did you use correct Launch ID?]
```

**Expected behavior**
API server should be able to fully manage its queues, if its unhealthy -> it should at least restart itself.  
A restart can triggered by a health check in kubernetes (for example).

**Screenshots**
#### Rabbitmq queues
You can see that the upper queues have queue 5 and 6 missing.  
In addition, queue 6 is missing from the second API server.  
![Image](https://github.com/user-attachments/assets/58f7f8c2-ebff-4130-bf94-768ec87aab8a)

#### API server resouce usage
![Image](https://github.com/user-attachments/assets/46b5e0c4-9abe-46b3-80d9-4fd6d49e5a4c)

![Image](https://github.com/user-attachments/assets/a9d0c15a-da7f-40ce-8ad8-6783ce0ed28b)

![Image](https://github.com/user-attachments/assets/ad339246-0d09-42b7-b640-5c639587f3c6)

**Versions:**
#### ReportPortal
reportportal/service-auto-analyzer:5.13.0
reportportal/service-api:5.13.0
reportportal/service-index:5.13.0
reportportal/service-jobs:5.13.0
reportportal/service-metrics-gatherer:5.12.0
reportportal/service-authorization:5.13.0
reportportal/service-ui:5.12.4

#### RabbitMQ
public.ecr.aws/bitnami/rabbitmq:3.13.7-debian-12-r5

**Comment by Pink-Bumblebee** [comment]
Hello @tomikonio , could you please tell us how many API servers are you using?

**Comment by tomikonio** [comment]
Hi @Pink-Bumblebee ,
We are using 2 API servers.

**Comment by Pink-Bumblebee** [comment]
@tomikonio , may I ask you : have you tried newest version of ReportPortal with Component Update? It was released on June, 10.

**Comment by tomikonio** [comment]
We have not.
Do you think the new version should fix this issue?

**Comment by Pink-Bumblebee** [comment]
Yes, as I heard, similar issue was fixed in latest release.

**Comment by tomikonio** [comment]
Ok, thank you @Pink-Bumblebee .
We will try the new version when we can.

In the meantime, can you please point me to the specific fixed issue?

**Comment by Pink-Bumblebee** [comment]
@tomikonio , sorry, I'm not a developer. I just consulted with them, showed your issue request and they said that "similar issue was fixed in latest release" version 25.1.

**Comment by tomikonio** [comment]
Hi.
We have updated to helm chart version `25.8.8` -> ReportPortal version - `25.1.6`.  
Sadly, we still have missing queues - and the API servers are not re-creating them - only a restart to the API server pods solves it.  

In here we have 3 API servers, and you can see that one of them has almost all of its queues missing, another API server also has some of its queues missing.
<img width="1260" height="610" alt="Image" src="https://github.com/user-attachments/assets/520c7679-2669-497a-b65a-c88b5b54c18f" />


Update:  
It became even worse - almost all queues have gone missing in here:

<img width="2422" height="1164" alt="Image" src="https://github.com/user-attachments/assets/474a3106-a01c-4873-995c-099e04978e27" />

(+ one queue - the one with 200k+ messages is not able to shovel itself).  
Any suggestions?

**Comment by tomikonio** [comment]
Hi @Pink-Bumblebee .
Any idea regarding the current situation?

**Comment by Pink-Bumblebee** [comment]
In the latest version 5.14.6 of analyzer (reportportal 25.1.12) looks like it was fixed. Please try this latest release.

**Comment by tomikonio** [comment]
Thank you for your response.
Isn't it the API servers the ones responsible for the `q.reporting.*` queues? Or does the analyzer play a role in here as well?

**Comment by yoavws** [comment]
This happens to us as well? can someone please take a look on this issue?

**Comment by tomikonio** [comment]
Hi @Pink-Bumblebee , any update on the matter?
Do you think that upgrading to the latest version of report-portal will solve the issue?

NOTE: we are talking about missing `reporting.*` queues.
The issue is still ongoing and gets worse from time - unless the API servers are restarted (by using `kubectl delete`) the system looses queues up to a point where it is unusable.

**Comment by droish** [comment]
Joining the thread as we've encountered the same behavior. Our RabbitMQ queues are disappearing without clear errors in the logs, leading to a complete halt in report processing.

@Pink-Bumblebee

**Comment by arkpotry** [comment]
Hello,

i was also struggling with crashing queues. The more intense testing was executed with reporting to RP, the more queues were crashing.

I was trying to investigate this issue, and i found out, that in RabbitMQ 4.1.2 there was a bug, which could randomly cause queue crash: https://github.com/rabbitmq/rabbitmq-server/discussions/14181.

Issue was fixed in RabbitMQ 4.1.5, and after update i did not see any queue crashing (3 weeks already)
