### ISSUE TITLE
Component Health Check (Table View) returns top level data on nested level

### ISSUE THREAD

**Issue by enumavalon** [reportportal/reportportal#2575]
**Describe the bug**
I created Component Health Check (table view) widget with multiple levels (5 levels).
The first 2 levels show correct info, but beyond that it returns the 1st (top) level info. Usually it would take a long time to load, and then it returns top level info. 
It used to work before, and I'm not sure why this is happening recently.

**Expected behavior**
Correct information will be displayed on every level

**Screenshots**
1st Level (E2EType attribute) (correct):

<img width="790" height="497" alt="Image" src="https://github.com/user-attachments/assets/09bf4eeb-c7ad-40a5-a69f-87d0ead66586" />

3rd Level (domain attribute):

<img width="816" height="523" alt="Image" src="https://github.com/user-attachments/assets/d52caa8c-8718-4c25-848c-8ffb996b7d00" />

4th Level (suite attribute):

<img width="814" height="515" alt="Image" src="https://github.com/user-attachments/assets/ecf0fd58-c3f2-4d03-8856-b20d7de71a5a" />

Test Case attributes:

<img width="982" height="825" alt="Image" src="https://github.com/user-attachments/assets/21ec71b2-ccdb-42ea-b831-016af13b3ab3" />

**Versions:**
 - Version of RP [25.0.4]

**Comment by Pink-Bumblebee** [comment]
Hello @enumavalon , it is not so easy to check what had happened without data that you have but we don't. It is need to reproduce issue to find the root cause and fix it. For now we released newer version with some fixes, and you could try it at demo.reportportal.io to check with your data.

**Comment by enumavalon** [comment]
Hi @Pink-Bumblebee, I was able to replicate the bug in demo.reportportal.io . I think the key here is if the attribute or test item name contains a comma, the widget shows top level information:

Test:

<img width="1920" height="998" alt="Image" src="https://github.com/user-attachments/assets/d64e206e-73df-4aaf-8c94-13f51fc952af" />

Widget: (test2 attribute shows top level instead of 'def' because previous level has comma)

<img width="1920" height="998" alt="Image" src="https://github.com/user-attachments/assets/6156d6b7-1f62-415f-a281-8e709521d296" />

As a workaround, I will be sanitizing input to remove commas.

**Comment by Pink-Bumblebee** [comment]
Hello @enumavalon , thank you for sharing results of your investigation. I will transfer them to Dev Team.

**Comment by Pink-Bumblebee** [comment]
Investigation showed that Reportportal uses commas as attribute pair delimiters. So, please avoid to using it inside one attribute.
Dev Team will put this case into backlog and fix it. But no ETA, sorry.

**Comment by enumavalon** [comment]
@Pink-Bumblebee I have sanitized the values in tags to not use commas, but the issue still occurs even on attributes without comma values. Would the suite/test item names affect the widget display? It's the only culprit I can think of now that I have sanitized the attribute values.

For example, I have comma value in the test name (not in the attribute). I also use other special characters in the item names which I suspect could be possible culprits (such as '&', '/', '()'). Could any of these cause the issue? Does Report Portal have a list of special characters we need to avoid in the item names?
