### ISSUE TITLE
[v5] parentstep still marked as in_progress after finish request send

### ISSUE THREAD

**Issue by mnicula** [reportportal/reportportal#934]
**Describe the bug**
parentstep still marked as in_progress after finish request send

**To Reproduce**
for a test that has following structure or similar:
*NestedStep -> nestedStep -> step*
send the finish request for each test item (_nestepStep_ first then for _NestedStep_)
**Expected behavior**
mentioned above nestedSteps are marked as passed/failed accordingly

**Screenshots**
![image](https://user-images.githubusercontent.com/48491734/80283903-c65fe580-8723-11ea-85ea-a3eed83d0528.png)

**Additional context**
Current version:API Service: 5.1.0;Index Service: 5.0.7;Authorization Service: 5.1.0;Service UI: 5.1.0;
If testcase structure is like this *NestedStep -> step1,step1, nestedStep* it works as expected
![image](https://user-images.githubusercontent.com/48491734/80284484-71be6980-8727-11ea-9aee-5459ce46b676.png)

**Comment by evjlobanova** [comment]
@svettsova Valya, could you please recheck this behavior, and create a ticket in Jira, if it is reproduced?

**Comment by svettsova** [comment]
@evjlobanova  It's reproducible for 5.1. and it was fixed in 5.2 version

**Comment by evjlobanova** [comment]
Thank you, Valya

**Comment by evjlobanova** [comment]
Version 5.2 will be available in the first dates of May

**Comment by mnicula** [comment]
I've upgraded RP to 5.2 version - issue is still reproducible

**Comment by svettsova** [comment]
So, I tried to reproduce it again and still have no issues. @mnicula could you help me with the steps?
I've reported Nested steps with the following structure:
![2020-05-19_16h40_57](https://user-images.githubusercontent.com/50825875/82317073-8b359700-99ef-11ea-890c-95f43bb554eb.png)
Then, I sent finish to NS-1 and after that to NS-2
As a result, I can see the correct statuses. Are my steps correct? Or maybe I need to reproduce it in another way?

**Comment by svettsova** [comment]
I also tried sending finish to NS-2 first, and then to NS-1 - but still have no issues

**Comment by mnicula** [comment]
Can you please try with some actual logs inside NS-2 on your side?

**Comment by svettsova** [comment]
![image](https://user-images.githubusercontent.com/50825875/82325833-adceac80-99fd-11ea-9243-dc24ec4f665a.png)
still have no issue. Do you perform steps directly to API or via some agent? 
I guess there is can be issue from agent which you use

**Comment by mnicula** [comment]
I use the API. Please try to log data only for NS-2, without having logs for NS-1

**Comment by svettsova** [comment]
![2020-05-19_18h35_08](https://user-images.githubusercontent.com/50825875/82326974-7bbe4a00-99ff-11ea-8056-f7717a010b68.png)
evrything is ok for me. Can we have a call via skype? live:valya.svettsova

**Comment by mnicula** [comment]
I will try it once again. Thanks for your help

**Comment by svettsova** [comment]
I will be much appreciated if you share your results :)

**Comment by mnicula** [comment]
Works ok, thanks. Sorry for bothering
